title : Ellie
name: 'Ellie'
description: 'Simple, light weight, responsive jekyll theme for hackers'

markdown: kramdown
highlighter: rouge
javascript_enabled: true

featured_posts_title: Unrelated
featured_posts:
  - url: '#'
    title: 'Featured post #1'
  - url: '#'
    title: 'Featured post #2'
  - url: '#'
    title: 'Featured post #3'

collections:
  news:
    title: Deep Work Conclusion
    default_open: false
    output: true
  posts:
    title: Deep Learning
    default_open: true
    output: true

defaults:
  - scope:
      type: posts
    values:
      title: Deep Learning
      permalink: /post/:title
  - scope:
      type: news
    values:
      title: Deep Work Conclusion
      permalink: /news/:title

plugins:
  - jekyll-sitemap
