title : Ellie
name: 'Ellie'
description: 'Simple, light weight, responsive jekyll theme for hackers'

markdown: kramdown
highlighter: rouge
javascript_enabled: true
collections:
  plans:
    title: Every Week Plan
    defult_open: false
    output: true
  posts:
    title: Deep Learning
    default_open: true
    output: true
  Deep Work:
    title: Deep Work Conclusion
    default_open: true
    output: true
    
defaults:
  - scope:
      type: plans
    values:
      title: Every Week Plan
      permalink: /plans/:title
  - scope:
      type: posts
    values:
      title: Deep Learning
      permalink: /post/:title
  - scope:
      type: Deep Work
    values:
      title: Deep Work Conclusion
      permalink: /Deep Work/:title
      
plugins:
  - jekyll-sitemap
