title : Ellie
name: 'Ellie'
description: 'Simple, light weight, responsive jekyll theme for hackers'

markdown: kramdown
highlighter: rouge
javascript_enabled: true
collections:
  news:
    title: Deep Work Conclusion
    default_open: false
    output: true
  plans:
    title: Every Week Plan
    defult_open: false
    output: true
  posts:
    title: Deep Learning
    default_open: true
    output: true

defaults:
  - scope:
      type: posts
    values:
      title: Deep Learning
      permalink: /post/:title
  - scope:
      type: news
    values:
      title: Deep Work Conclusion
      permalink: /news/:title
  - scope:
      type: plans
    values:
      title: Every Week Plan
      permalink: /news/:title

plugins:
  - jekyll-sitemap
